CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX ux_users_username ON users (username);

INSERT INTO items (name, description) VALUES
    ('Demo Item Alpha', 'First clean demo item for the secure branch'),
    ('Demo Item Beta', 'Second clean demo item for CRUD walkthroughs'),
    ('Demo Item Gamma', 'Third clean demo item for search walkthroughs');

INSERT INTO users (username, password_hash) VALUES
    ('demo', '$2b$10$VVr6UQq7OkrylXcc/UuGReRXWEvPKONqedNRcGsAwMHUUFVD1VrPG');
