version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    groups:
      backend-maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    groups:
      frontend-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
