apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ghas-defender-example
  annotations:
    kubernetes.azure.com/ingress.class: webapprouting.kubernetes.azure.com
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - {{ .Env.AZURE_BACKEND_INGRESS_HOSTNAME }}
      secretName: backend-tls
  rules:
    - host: {{ .Env.AZURE_BACKEND_INGRESS_HOSTNAME }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
