apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: ghas-defender-example
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "{{ .Env.AZURE_BACKEND_IDENTITY_CLIENT_ID }}"
